name: ai
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- asn1crypto=0.24.0=py36_0
- blas=1.0=mkl
- cffi=1.11.5=py36h342bebf_0
- chardet=3.0.4=py36h96c241c_1
- cryptography=2.2.2=py36h1de35cc_0
- flask-cors=3.0.6=py36_0
- idna=2.6=py36h8628d0a_1
- inflection=0.3.1=py36_0
- intel-openmp=2018.0.3=0
- jpeg=9b=he5867d9_2
- libgfortran=3.0.1=h93005f0_2
- libtiff=4.0.9=hcb84e12_1
- mkl=2018.0.3=1
- mkl_fft=1.0.1=py36h917ab60_0
- mkl_random=1.0.1=py36h78cc56f_0
- more-itertools=4.2.0=py36_0
- numpy=1.14.5=py36h9bb19eb_0
- numpy-base=1.14.5=py36ha9ae307_0
- olefile=0.45.1=py36_0
- pandas=0.23.1=py36h1702cab_0
- pillow=5.1.0=py36hfcce615_0
- pycparser=2.18=py36h724b2fc_1
- pyopenssl=18.0.0=py36_0
- pysocks=1.6.8=py36_0
- python-dateutil=2.7.3=py36_0
- pytz=2018.4=py36_0
- quandl=3.3.0=py36_0
- requests=2.18.4=py36h4516966_1
- scikit-learn=0.19.1=py36hffbff8c_0
- scipy=1.1.0=py36hcaad992_0
- six=1.11.0=py36h0e22d5e_1
- urllib3=1.22=py36h68b9469_0
- absl-py=0.2.2=py_0
- aniso8601=3.0.2=py36_0
- astor=0.6.2=py_0
- bleach=1.5.0=py36_0
- click=6.7=py_1
- cycler=0.10.0=py36_0
- flask=1.0.2=py_1
- flask-restful=0.3.6=py36_0
- freetype=2.8.1=0
- gast=0.2.0=py_0
- html5lib=0.9999999=py36_0
- itsdangerous=0.24=py_2
- jinja2=2.10=py36_0
- kiwisolver=1.0.1=py36_1
- libpng=1.6.34=0
- libprotobuf=3.5.2=0
- markdown=2.6.11=py_0
- markupsafe=1.0=py36_0
- matplotlib=2.2.2=py36_1
- protobuf=3.5.2=py36_0
- pycrypto=2.6.1=py36_1
- pyparsing=2.2.0=py36_0
- tensorboard=1.8.0=py36_1
- tensorflow=1.8.0=py36_1
- tensorflow-hub=0.1.0=py_0
- termcolor=1.1.0=py36_1
- tornado=5.0.2=py36_0
- webencodings=0.5.1=py36_0
- werkzeug=0.14.1=py_0
- ca-certificates=2018.03.07=0
- certifi=2018.4.16=py36_0
- grpcio=1.12.1=py36hd9629dc_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1.20170329=hb402a30_2
- libffi=3.2.1=h475c297_4
- ncurses=6.1=h0a44026_0
- openssl=1.0.2o=h26aff7b_0
- pip=10.0.1=py36_0
- python=3.6.5=hc167b69_1
- readline=7.0=hc1231fa_4
- setuptools=39.2.0=py36_0
- sqlite=3.23.1=hf1716c9_0
- tk=8.6.7=h35a86e2_3
- wheel=0.31.1=py36_0
- xz=5.2.4=h1de35cc_4
- zlib=1.2.11=hf3cbc9b_2
- pip:
  - appnope==0.1.0
  - astroid==1.6.5
  - autopep8==1.3.5
  - decorator==4.1.2
  - ipykernel==4.6.1
  - ipython==6.2.1
  - ipython-genutils==0.2.0
  - isort==4.3.4
  - jedi==0.11.0
  - jupyter-client==5.1.0
  - jupyter-core==4.4.0
  - lazy-object-proxy==1.3.1
  - mccabe==0.6.1
  - metakernel==0.20.12
  - mkl-fft==1.0.0
  - mkl-random==1.0.1
  - parso==0.1.0
  - pexpect==4.3.0
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - pycodestyle==2.4.0
  - pygments==2.2.0
  - pylint==1.9.2
  - pyzmq==16.0.3
  - simplegeneric==0.8.1
  - traitlets==4.3.2
  - virtualenv==15.2.0
  - wcwidth==0.1.7
  - wrapt==1.10.11
prefix: /Users/jo/anaconda3/envs/ai

